[package]
name = "look"
version = "0.0.0-git"
edition = "2021"

[dependencies]
egui = { version = "0.21", default-features = false }
crossbeam-channel = "0.5"
tracing = "0.1"
uuid = "1.3"

vitamin = { path = "../vitamin" }
